services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - database
    env_file:
      - .env
  database:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"